[project]
name = "ai-research-assistant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "acyncio",
    "dotenv>=0.9.9",
    "logging>=0.4.9.6",
    "nest-acyncio",
    "openai>=3.7.0",
    "pydantic>=2.13.5",
    "tavily>=1.1.0",
]
